# Generated by Django 4.2.6 on 2023-10-06 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reels_app', '0003_user_profile_user_alter_user_profile_profile_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_liked_by',
            new_name='LikedBy',
        ),
        migrations.RenameModel(
            old_name='Tags_on_post',
            new_name='SharedPost',
        ),
        migrations.RenameField(
            model_name='sharedpost',
            old_name='tags',
            new_name='shared_to',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='Profile_picture',
            new_name='ProfilePicture',
        ),
        migrations.AlterModelTable(
            name='likedby',
            table='likedby',
        ),
        migrations.AlterModelTable(
            name='posts',
            table='posts',
        ),
        migrations.AlterModelTable(
            name='sharedpost',
            table='sharedPost',
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reels_app.posts')),
                ('taged_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
    ]
