# Generated by Django 4.2.6 on 2023-10-06 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reels_app', '0004_rename_post_liked_by_likedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedpost',
            name='shared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharedpost',
            name='shared_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
