# Generated by Django 4.2.6 on 2023-10-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reels_app', '0007_comments_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_profile',
            table='user_profile',
        ),
    ]
