# Generated by Django 4.2.6 on 2023-10-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reels_app', '0009_followers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='followers',
            table='followers',
        ),
    ]
